---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 32
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "B"
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- config/
- fixtures/
- dummy-korben/
- "**/migrations/"
- "**.yml"
- "**.xml"
- "**.txt"
- "**.rst"
- "**.sh"
- Dockerfile
- "**/test/"
- "**/tests/"


