version: '2'
services:

  leeloo-common:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: |
        dockerize -wait tcp://postgres:5432 -timeout 60s
    environment:
      SECRET_KEY: foobar
      DATABASE_URL: postgresql://postgres@postgres/datahub
      DATAHUB_SECRET: secret
      DEBUG: 'True'
      DJANGO_SECRET_KEY: changeme
      DJANGO_SETTINGS_MODULE: config.settings.local
      COV_TOKEN: ${COV_TOKEN}
      KORBEN_HOST: korben
      KORBEN_PORT: 8080

  leeloo:
    extends:
      service: leeloo-common
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - korben
    links:
      - postgres
      - korben
    command: /app/start.sh

  korben:
    build:
      context: dummy-korben
    ports:
      - "8080:8080"

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_DB=datahub
